from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404, get_list_or_404, redirect
from django.forms import modelform_factory

from meetings.models import Meeting, Room


def detail(request, id):
    #    meeting = Meeting.objects.get(pk=id) pk->primary key-> the row with this unique id
    meeting = get_object_or_404(Meeting, pk=id)
    return render(request, "meetings/detail.html", {"meeting": meeting})


def rooms(request):
    return render(request, "meetings/rooms.html",
                  {"rooms": Room.objects.all()})

MeetingForm = modelform_factory(Meeting, exclude=[]) #this is a class generated by django

def new(request):
    if request.method == "POST":
        #for was submited, process data
        form = MeetingForm(request.POST)
        if form.is_valid():
            form.save() #saves it in the database
            return redirect("home")
    else:
        form = MeetingForm()
    return render(request, "meetings/new.html", {"form": form})